import{a as f,i as d,S as b}from"./assets/vendor-YT4DRQk6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const w=f.create({baseURL:"https://pixabay.com/api/",params:{key:"48884243-7c5376715b9f7ca682882ed04",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"40"}});async function m(e,r){try{const s=await w.get("",{params:{q:e,per_page:40,page:r}});return s.data.hits.length===0?(d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}):{hits:s.data.hits,totalHits:s.data.totalHits}}catch{return d.error({title:"Error",message:"Please try again",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}}}const n={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".more-btn")};function y(e){const r=S(e);n.gallery.innerHTML+=r,n.gallery.classList.add("gallery");const s=e.length?e[0].totalHits:0;n.gallery.children.length>=s?(n.loadMoreBtn.style.display="none",iziToast.error({title:"Error",messages:"We're sorry, but you've reached the end of search results",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"})):n.loadMoreBtn.style.display="block"}function L(){n.gallery.innerHTML=""}function q(e){const{webformatURL:r,largeImageURL:s,tags:o,likes:t,views:a,comments:i,downloads:p}=e;return`<li class="js-gallery-item">
        <a href="${s}">
        <img src="${r}" alt="${o}" width="360" height="158"/>
        </a>
        <ul class="stats">
          <li class="stats-item">Likes<span class="stats-span">${t}</span></li>
          <li class="stats-item">Comments<span class="stats-span">${i}</span></li>
          <li class="stats-item">Views<span class="stats-span">${a}</span></li>
          <li class="stats-item">Downloads<span class="stats-span">${p}</span></li>
        </ul>
      </li>`}function S(e){return e.map(q).join("")}function H(){const e=document.querySelector(".js-gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*3.2,behavior:"smooth"})}const l={searchForm:document.querySelector(".js-search-form"),loader:document.querySelector(".js-loader"),gallery:document.querySelector(".js-gallery"),loadMoreBtn:document.querySelector(".more-btn")};let u="",c=1,g=new b(".gallery a");l.searchForm.addEventListener("submit",M);async function M(e){e.preventDefault(),u=e.target.elements["search-bar"].value.trim(),L(),l.loadMoreBtn.style.display="none",l.loader.style.display="block",c=1;const s=await m(u,c),{hits:o,totalHits:t}=s;o.length===0?d.error({title:"Error",message:"Invalid query. Try again"}):(y(o),g.refresh()),h(o,t),l.loader.style.display="none",e.target.reset()}l.loadMoreBtn.addEventListener("click",C);async function C(){l.loader.style.display="block",c++;const e=await m(u,c),{hits:r,totalHits:s}=e;y(r),g.refresh(),h(r,s),l.loader.style.display="none",H()}function h(e,r){(e.length<40||c*40>=r)&&(l.loadMoreBtn.style.display="none",l.loader.style.display="none",d.info({message:"No more images could be found under the current query"}))}
//# sourceMappingURL=index.js.map
