import{a as f,i as c,S as b}from"./assets/vendor-YT4DRQk6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const w=f.create({baseURL:"https://pixabay.com/api/",params:{key:"48884243-7c5376715b9f7ca682882ed04",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"40"}});async function y(e,r){try{const s=await w.get("",{params:{q:e,per_page:40,page:r}});return s.data.hits.length===0?(c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}):{hits:s.data.hits,totalHits:s.data.totalHits}}catch{return c.error({title:"Error",message:"Please try again",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}}}const n={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".more-btn")};function m(e){const r=M(e);n.gallery.innerHTML+=r,n.gallery.classList.add("gallery");const s=e.length?e[0].totalHits:0;n.gallery.children.length>=s?(n.loadMoreBtn.style.display="none",iziToast.error({title:"Error",messages:"We're sorry, but you've reached the end of search results",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"})):n.loadMoreBtn.style.display="block"}function L(){n.gallery.innerHTML=""}function q(e){const{webformatURL:r,largeImageURL:s,tags:l,likes:t,views:o,comments:i,downloads:p}=e;return`<li class="js-gallery-item">
        <a href="${s}">
        <img src="${r}" alt="${l}" width="360" height="158"/>
        </a>
        <ul class="stats">
          <li class="stats-item">Likes<span class="stats-span">${t}</span></li>
          <li class="stats-item">Comments<span class="stats-span">${i}</span></li>
          <li class="stats-item">Views<span class="stats-span">${o}</span></li>
          <li class="stats-item">Downloads<span class="stats-span">${p}</span></li>
        </ul>
      </li>`}function M(e){return e.map(q).join("")}function S(){const e=document.querySelector(".js-gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*3.2,behavior:"smooth"})}const a={searchForm:document.querySelector(".js-search-form"),loader:document.querySelector(".js-loader"),gallery:document.querySelector(".js-gallery"),loadMoreBtn:document.querySelector(".more-btn")};let u="",d=1,g;a.searchForm.addEventListener("submit",H);async function H(e){e.preventDefault(),u=e.target.elements["search-bar"].value,L(),a.loadMoreBtn.style.display="none",a.loader.style.display="block",d=1;const s=await y(u,d),{hits:l,totalHits:t}=s;l.length===0?c.error({title:"Error",message:"Invalid query. Try again"}):(m(l),g=new b(".gallery a")),h(l),t>40&&(a.loadMoreBtn.style.display="block"),a.loader.style.display="none",e.target.reset()}a.loadMoreBtn.addEventListener("click",k);async function k(){a.loader.style.display="block";const e=await y(u,d),{hits:r,totalHits:s}=e;m(r),h(r),g.refresh(),d++,C(s),a.loader.style.display="none",S()}function h(e){e.length<40&&(a.loadMoreBtn.style.display="none",a.loader.style.display="none",c.info({message:"No more images could be found under the current query"}))}function C(e){d*40>=e&&(a.loadMoreBtn.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."}))}
//# sourceMappingURL=index.js.map
