import{a as h,i as d,S as p}from"./assets/vendor-YT4DRQk6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const f=h.create({baseURL:"https://pixabay.com/api/",params:{key:"48884243-7c5376715b9f7ca682882ed04",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"40"}});async function y(e,r){try{const s=await f.get("",{params:{q:e,per_page:40,page:r}});return s.data.hits.length===0?(d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}):{hits:s.data.hits,totalHits:s.data.totalHits}}catch{return d.error({title:"Error",message:"Please try again",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),{hits:[],totalHits:0}}}const n={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".more-btn")};function m(e){const r=L(e);n.gallery.innerHTML+=r,n.gallery.classList.add("gallery"),new p(".gallery a").refresh();const o=e.length?e[0].totalHits:0;n.gallery.children.length>=o?(n.loadMoreBtn.style.display="none",iziToast.error({title:"Error",messages:"We're sorry, but you've reached the end of search results",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"})):n.loadMoreBtn.style.display="block"}function b(){n.gallery.innerHTML=""}function w(e){const{webformatURL:r,largeImageURL:s,tags:o,likes:t,views:a,comments:i,downloads:g}=e;return`<li class="js-gallery-item">
        <a href="${s}">
        <img src="${r}" alt="${o}" width="360" height="158"/>
        </a>
        <ul class="stats">
          <li class="stats-item">Likes<span class="stats-span">${t}</span></li>
          <li class="stats-item">Comments<span class="stats-span">${i}</span></li>
          <li class="stats-item">Views<span class="stats-span">${a}</span></li>
          <li class="stats-item">Downloads<span class="stats-span">${g}</span></li>
        </ul>
      </li>`}function L(e){return e.map(w).join("")}function M(){const e=document.querySelector(".js-gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*3.2,behavior:"smooth"})}const l={searchForm:document.querySelector(".js-search-form"),loader:document.querySelector(".js-loader"),gallery:document.querySelector(".js-gallery"),loadMoreBtn:document.querySelector(".more-btn")};let u="",c=1;l.searchForm.addEventListener("submit",q);async function q(e){e.preventDefault(),u=e.target.elements["search-bar"].value,b(),l.loadMoreBtn.style.display="none",l.loader.style.display="block",c=1;const s=await y(u,c),{hits:o,totalHits:t}=s;o.length===0?d.error({title:"Error",message:"Invalid query. Try again"}):m(o),t>40&&(l.loadMoreBtn.style.display="block"),l.loader.style.display="none",e.target.reset()}l.loadMoreBtn.addEventListener("click",S);async function S(){l.loader.style.display="block";const e=await y(u,c),{hits:r,totalHits:s}=e;m(r),c++,H(s),l.loader.style.display="none",M()}function H(e){c*40>=e&&(l.loadMoreBtn.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results."}))}
//# sourceMappingURL=index.js.map
